name: pull-request

on:
  - pull_request

jobs:
  unit-test:
    strategy:
      matrix:
        go-version: [1.16.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Run unit tests
        run: make test
  lint:
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x, 1.14.x]
        platform: [ubuntu-latest]
        arch: [386, amd64, arm, arm64]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Run Linter
        run: make lint
  build-test:
    strategy:
      matrix:
        go-version: [1.16.x]
        platform: [ubuntu-latest]
        arch: [386, amd64, arm, arm64]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Building binary
        run: GOARCH=${{ matrix.arch }} make build